# Default settings
server:
  port: 8010
---
# Development settings
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mariadb://100.100.10.177:3306/INVENIA_DEV"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "e1264"
    password: "inveni@2020"
  cloud:
    config:
      enabled: false

---
# Product settings
spring:
  config:
    import: "optional:configserver:"
    activate:
      on-profile: prod
  application:
    name: erp-service
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0*
        - eth2*
    config:
      discovery:
        enabled: true # 유레카에서 검색
management:
  endpoint:
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
  health:
    diskspace:
      enabled: true
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka} # 유레카 서비스 위치


